id: P000697
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-16 16:37:38.954287
source_metadata:
  id: bdr:W4CZ45310
  title: བརྒྱད་སྟོང་པ།  ༼གསེར་བྲིས།༽
  author: ''
  volumes:
    5652117d3f814beca8a050354632760f:
      image_group_id: I4CZ75169
      title: ''
      volume_number: 1
      total_pages: 643
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
