id: IE438978C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T22:44:44+00:00'
last_modified: '2022-06-07T12:41:22.475473+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ45310
  title: བརྒྱད་སྟོང་པ།  ༼གསེར་བྲིས།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8439':
      image_group_id: I4CZ75169
      title: ''
      total_pages: 643
      order: 1
      base_file: 8439.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
